isProduction: false
bitrixProxy: false
baseUrl: https://www.oat.ru/
mainUrl: https://www.oat.ru/
bindPort: 20045
database:
    address: "node-4.taigo.xyz"
    port: 3306
    name: s243_oat
    username: "u243_FamdORgAVM"
    password: "FN0YDnWg5^n+J00dJTGx3H80"
ldap:
    address: "178.74.67.83"
    port: 789
    username: "ld"
    password: "ldaps332!@"
    domain: "elki55"
    zone: "ru"
telegram:
    apiKey: '7034459389:AAGY0oiHeNKGcY_51XEahzmAXOuAtLxVB5Y'
    logChatId: -1001909586864
    newsChannelId: -1002352511070
    newsEloChannelId: -1002690593740
