isProduction: false
bitrixProxy: false
baseUrl: https://www.oat.ru/
mainUrl: https://www.oat.ru/
bindPort: 20045
database:
    address: "node.taigo.xyz"
    port: 3306
    name: s126_OAT
    username: "u126_FTgyBjq2cl"
    password: "qYqy6O.MgSk!lm54ieYlnhly"
ldap:
    address: "178.74.67.83"
    port: 789
    username: "ld"
    password: "ldaps332!@"
    domain: "elki55"
    zone: "ru"
telegram:
    apiKey: '7034459389:AAGY0oiHeNKGcY_51XEahzmAXOuAtLxVB5Y'
    logChatId: -1001909586864
    newsChannelId: -1002352511070
    newsPublishTag: '#омавиат_сайт'
