baseUrl: https://www.oat.ru
mainUrl: http://localhost:20045
bindPort: 20045
dbIp: "taigo.xyz"
dbPort: 3306
dbUser: "u20_tqSmWnicfV"
dbPassword: "4seGYYxlRNOa9@!EGVw1ZqiB"
dbName: s20_oat
ldapIP: "178.74.67.83"
ldapPort: 789
ldapLogin: "ld"
ldapPassword: "ldaps332!@"
ldapDomain: "elki55"
ldapZone: "ru"
