// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMAVIAT;

#nullable disable

namespace OMAVIAT.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240825060028_TypeOfLoad")]
    partial class TypeOfLoad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OMAVIAT.Entities.Database.CMK", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("achievements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("compositions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descriptionOfWork")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("history")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("plans")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("CMK");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Database.DemoExamNews", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsFixed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("photos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("short_description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("DemoExamNews");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Database.Documents", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Database.IPTables", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("BanTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastFailAttempt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("attempts")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("IPTables");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Database.News", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsFixed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("photos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("short_description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Database.ProfNews", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsFixed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("photos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("short_description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ProfNews");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Database.Tokens", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("issued")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Schedule.Bell", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int?>("DaysChangesTableid")
                        .HasColumnType("int");

                    b.Property<string>("id")
                        .HasColumnType("longtext");

                    b.Property<string>("period")
                        .HasColumnType("longtext");

                    b.HasKey("TableId");

                    b.HasIndex("DaysChangesTableid");

                    b.ToTable("Bell");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Schedule.Database.AcademicLoad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CompletedHours")
                        .HasColumnType("double");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("int");

                    b.Property<double>("TotalHours")
                        .HasColumnType("double");

                    b.Property<string>("TypeOfLoad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AcademicLoads");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Schedule.Database.ChangesTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cabinet")
                        .HasColumnType("longtext");

                    b.Property<int>("corpus")
                        .HasColumnType("int");

                    b.Property<int?>("couple")
                        .HasColumnType("int");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("discipline")
                        .HasColumnType("longtext");

                    b.Property<string>("group")
                        .HasColumnType("longtext");

                    b.Property<string>("reason")
                        .HasColumnType("longtext");

                    b.Property<string>("teacher")
                        .HasColumnType("longtext");

                    b.Property<string>("was_cabinet")
                        .HasColumnType("longtext");

                    b.Property<int?>("was_couple")
                        .HasColumnType("int");

                    b.Property<string>("was_discipline")
                        .HasColumnType("longtext");

                    b.Property<string>("was_teacher")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("changes");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Schedule.Database.DaysChangesTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DateText")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolWeek")
                        .HasColumnType("longtext");

                    b.Property<int>("corpus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("type")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("daysChanges");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Schedule.Bell", b =>
                {
                    b.HasOne("OMAVIAT.Entities.Schedule.Database.DaysChangesTable", null)
                        .WithMany("bells")
                        .HasForeignKey("DaysChangesTableid");
                });

            modelBuilder.Entity("OMAVIAT.Entities.Schedule.Database.DaysChangesTable", b =>
                {
                    b.Navigation("bells");
                });
#pragma warning restore 612, 618
        }
    }
}
