[
    "Разговоры о важном",
    "Разговор о важном",
    "ПМ.03 Разработка, моделирование и оптимизация мехатронных систем",
    "ПМ.03 Разработка, моделирование и оптимизация мехатронных систем",
    "ПМ 01 Подготовка и осуществление технологических процессов изготовления сварных конструкций",
    "ПМ.04 Организация и планирование сварочного производства",
    "ПМ.05 Организация деятельности подчиненного персонала (Курсовой проект)",
    "ПМ.05 Осуществление налогового учета и налогового планирования в организации(курсовой проект)",
    "ПМ.05 Осуществление налогового учета и налогового планирования в организации(курсовой проект)",
    "ПМ.02 Социальная работа с семьёй и детьми (курсовой проект)",
    "ПМ.02 Управление логистическими процессами",
    "ПМ.02 Разработка и внедрение управляющих программ изготовления деталей машин в машиностроительном производстве",
    "ПМ.01 Разработка технологических процессов и управляющих программ для изготовления деталей в металлообрабатывающих и аддитивных производствах (Курсоваой проект)",
    "Общая физическая подготовка"
]
