name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
           
        - name: Publish project
          run: dotnet publish -c Release

        - name: Generate release tag
          id: generate_release_tag
          uses: alexvingg/next-release-tag@v1.0.4
          with:
            github_token: ${{ secrets.git_token }}
            tag_prefix: ''

        - name: Create Zip File
          uses: papeloto/action-zip@v1
          with:
            files: "OAT/OMAVIAT/bin/Release/net8.0/linux-x64/publish/*"
            dest: "OAT/OMAVIAT/bin/Release/net8.0/linux-x64/publish/release.zip"
          
        - name: Initialize Release
          uses: actions/create-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.git_token }}
          with:
            tag_name: ${{ steps.generate_release_tag.outputs.release_tag }}
            release_name: ${{ steps.generate_release_tag.outputs.release_tag }}
      
        - name: Create Release    
          uses: csexton/release-asset-action@v2
          with:
            github-token: ${{ secrets.git_token }}
            file: "OAT/OMAVIAT/bin/Release/net8.0/linux-x64/publish/release.zip"
            release-url: ${{ steps.create_release.outputs.upload_url }} 

