name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
            
        - name: set env
          run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')" 
    
        - name: Install dependencies
          run: dotnet restore
          
        - name: Test with dotnet
          run: dotnet publish 
          
        - name: Upload dotnet results
          uses: actions/upload-artifact@v4
          with:
            name: Build-app-${{ env.NOW }}
            path: /OAT
