name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
           
 
        - name: Install dependencies
          run: dotnet restore
          
        - name: Publish project
          run: dotnet publish -c Release

        - name: Generate release tag
          id: generate_release_tag
          uses: alexvingg/next-release-tag@v1.0.4
          with:
            github_token: ${{ secrets.git_token }}
            tag_prefix: ''

        - name: Upload dotnet results
          uses: actions/upload-artifact@v4
          with:
            name: ${{ steps.generate_release_tag.outputs.release_tag }}
            path: OAT/OMAVIAT/bin/Release/net8.0/linux-x64/publish/
